Shelter.create(name: "Happy Paws", address: "San Diego, CA")
Shelter.create(name: "Pet Kisses", address: "Miami, FL")
Shelter.create(name: "Furry Friends", address: "New York, NY")
Shelter.create(name: "ASPCA", address: "Houston, TX")
Shelter.create(name: "MSPCA", address: "Boston, MA")

Adopter.create(first_name: "Ann", last_name: "M")
Adopter.create(first_name: "Stu", last_name: "M")
Adopter.create(first_name: "Rose", last_name: "F")
Adopter.create(first_name: "Pat", last_name: "F")
Adopter.create(first_name: "Tony", last_name: "F")


Pet.create(name: "Kitty", age: 1, species: "feline", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.create(name: "Henry", age: 2, species: "canine", adopted?: false, shelter_id: 2, adopter_id: nil)
Pet.create(name: "Buckle", age: 3, species: "feline", adopted?: false, shelter_id: 3, adopter_id: nil)
Pet.create(name: "Pepper", age: 4, species: "canine", adopted?: false, shelter_id: 4, adopter_id: nil)
Pet.create(name: "Fran", age: 5, species: "feline", adopted?: false, shelter_id: 5, adopter_id: nil)
Pet.create(name: "Snoopy", age: 6, species: "canine", adopted?: true, shelter_id: 1, adopter_id: nil)
Pet.create(name: "Happy", age: 7, species: "feline", adopted?: false, shelter_id: 3, adopter_id: nil)
Pet.create(name: "Pickles", age: 8, species: "canine", adopted?: false, shelter_id: 5, adopter_id: nil)
Pet.create(name: "Lady", age: 9, species: "feline", adopted?: false, shelter_id: 3, adopter_id: nil)
Pet.create(name: "Paulie", age: 10, species: "canine", adopted?: false, shelter_id: 2, adopter_id: nil)