Shelter.new(name: "", address: "")
Shelter.new(name: "", address: "")
Shelter.new(name: "", address: "")
Shelter.new(name: "", address: "")
Shelter.new(name: "", address: "")

Adopter.new(first_name: "Ann", last_name: "")
Adopter.new(first_name: "Stu", last_name: "")
Adopter.new(first_name: "", last_name: "")
Adopter.new(first_name: "", last_name: "")
Adopter.new(first_name: "", last_name: "")


Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)