Shelter.new(name: "Happy Paws", address: "")
Shelter.new(name: "Pet Kisses", address: "")
Shelter.new(name: "Furry Friends", address: "")
Shelter.new(name: "ASPCA", address: "")
Shelter.new(name: "MSPCA", address: "")

Adopter.new(first_name: "Ann", last_name: "M")
Adopter.new(first_name: "Stu", last_name: "M")
Adopter.new(first_name: "Rose", last_name: "F")
Adopter.new(first_name: "Pat", last_name: "F")
Adopter.new(first_name: "Tony", last_name: "F")


Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)