Shelter.new(name: "Happy Paws", address: "San Diego, CA")
Shelter.new(name: "Pet Kisses", address: "Miami, FL")
Shelter.new(name: "Furry Friends", address: "New York, NY")
Shelter.new(name: "ASPCA", address: "Houston, TX")
Shelter.new(name: "MSPCA", address: "Boston, MA")

Adopter.new(first_name: "Ann", last_name: "M")
Adopter.new(first_name: "Stu", last_name: "M")
Adopter.new(first_name: "Rose", last_name: "F")
Adopter.new(first_name: "Pat", last_name: "F")
Adopter.new(first_name: "Tony", last_name: "F")


Pet.new(name: "Kitty", age: 1, species: "feline", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "Henry", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "Buckle", age: 1, species: "feline", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "Pepper", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "French", age: 1, species: "feline", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "feline", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "feline", adopted?: false, shelter_id: 1, adopter_id: nil)
Pet.new(name: "", age: 1, species: "canine", adopted?: false, shelter_id: 1, adopter_id: nil)